targets:
  $default:
    builders:
      graphql_codegen:
        options:
          scalars:
            ISODateTime:
              type: DateTime
            DateTime:
              type: DateTime
            Date:
              type: DateTime
            JSONString:
              type: Map<String, dynamic>
            JSON:
              type: Map<String, dynamic>
            #Пока используем double возможно потом тип поменяется
            PositiveDecimal:
              type: double 